### ISSUE TITLE
Field not displayed in Filament v3

### ISSUE THREAD

**Issue by kylekanderson** [creagia/filament-code-field#20]
When using this plug-in with Filament v3 (v2 of the plugin), I'm seeing the following error message in the console:
![2023-08-15 at 16 46 56](https://github.com/creagia/filament-code-field/assets/24831484/6a9b30dc-e81b-455f-b237-4b2e1a526406)

I believe this is originating from here:
![2023-08-15 at 16 47 08](https://github.com/creagia/filament-code-field/assets/24831484/d30a762e-882e-4d26-8a6d-c7b2bb0d8786)

This is preventing the field from rendering on the page.

Update: this only happens when casting a property to json via the model. When I remove the json casting, it works as expected.

Below is the content of the property I'm trying to display:

> [
    [
      "slug" => "practical-suggestions",
      "rating" => 3,
    ],
    [
      "slug" => "innovative-material",
      "rating" => 4,
    ],
    [
      "slug" => "increased-awareness",
      "rating" => 3,
    ],
    [
      "slug" => "well-organized",
      "rating" => 2,
    ],
    [
      "slug" => "well-articulated",
      "rating" => 4,
    ],
    [
      "slug" => "overall",
      "rating" => 4,
    ],
  ]

**Comment by KostasKostogloy** [comment]
@kylekanderson  To keep the json casting I came up with this workaround:
<img width="852" alt="image" src="https://github.com/creagia/filament-code-field/assets/7452129/e6c4ca0e-bc15-40f5-bc42-f9cd2dcf25f9">

**Comment by ricardcreagia** [comment]
I can’t find a way to reproduce this issue. Are you using the latest version of the plugin? I know we fixed this at some point.

I’m closing it for now - feel free to reopen it if you find a way to create a reproducible repository. Thanks!
