### ISSUE TITLE
After update to 1.0.2 json not properly formatted?

### ISSUE THREAD

**Issue by ziming** [creagia/filament-code-field#3]
I recently did a composer update and now my codefield looks like this with a lot of \n when displaying json. Previously it looks like a well formatted json. This happen in multiple projects after I update this package to 1.0.2

![CleanShot 2023-01-18 at 11 41 56@2x](https://user-images.githubusercontent.com/679513/213078688-a78fa487-f850-4e81-add0-51a489392e9b.png)

Update: I could not reproduce this locally but on my staging servers and my production servers, this happens since today for all old and new records in filament admin

**Comment by ricardcreagia** [comment]
Hello ziming.

Should be fixed in v1.0.3.

Can you please update the package and force reload the cache to get the latest script file?

Thanks

**Comment by ziming** [comment]
Thank you it works now. I looked at your commit. Maybe earlier you are trying to do json formatting if it is a unformatted raw json string.

Thought I share my filament code when i use your code field so you can achieve what you want without breaking

```php
// json_data is casted to array in my model class

CodeField::make('json_data')->afterStateHydrated(function (?array $state, CodeField $component): void {
                        $component->state(json_encode($state, JSON_PRETTY_PRINT));
                    })->disabled()->dehydrated(false),
```

**Comment by ricardcreagia** [comment]
Glad it worked now and thanks for sharing 👍
