### ISSUE TITLE
ReferenceError: Can't find variable: filamentCodeField

### ISSUE THREAD

**Issue by madsem** [creagia/filament-code-field#4]
Hey,

thanks a lot for this plugin :) 

I'm sure it's a noob mistake, but for some reason I am having issues making it work.
Installed via composer, set up a simple CodeField but I then get the JS error in title...

```php
    public array $waterfall_log = [];


    public function mount(): void
    {
        $this->authorize('view', $this->lead);

        $this->form->fill([
            'waterfall_log' => $this->lead->log->waterfall_log,
        ]);
    }


    protected function getFormSchema(): array
    {
        return [
            
            CodeField::make('waterfall_log')
                ->disableAutocompletion()
                ->withLineNumbers()
                ->disabled(),

        ];
    }
```

I tried running `npm run dev` but the JS error persists.

PS: I'm using the CodeField with Filament Form Builder

**Comment by ricardcreagia** [comment]
Looks like an issue with the code field when used in the form builder instead of the admin panel.

Thanks for reporting this. I'll take a look and keep you updated. 

Thanks!

**Comment by madsem** [comment]
Ahhhhh! Thanks so much @ricardcreagia  :)
it all makes sense now haha, appreciate your help!
