### ISSUE TITLE
Specify height of code field

### ISSUE THREAD

**Issue by hackel** [creagia/filament-code-field#7]
Please consider providing a way to specify the height of a code field, either in number of lines or pixels, with a scrollbar for the overflow.  Currently the field height is set to the length of the content, which can get to be extremely long.  Thanks!

**Comment by ricardcreagia** [comment]
Thanks for your suggestion. I have released `v1.0.6` with the ability to set a min and max height to the input.

Usage:
```PHP  
CodeField::make('code')
    ->jsField()
    ->minHeight(200)
    ->maxHeight('500px'),
```

**Comment by ricardcreagia** [comment]
Ops, I think that was my mistake. Should be working now (in `1.0.7`), can you check?

**Comment by hackel** [comment]
@ricardcreagia Yes, now it works great, thanks again!
